#!/bin/bash
#
# Init file for Joget
#
# chkconfig: 2345 55 25
# description: Joget Tomcat server
#
# Source function library.
. /etc/init.d/functions
CATALINA_HOME=/opt/joget-linux-3.0.3/apache-tomcat-6.0.18 # Adjust to Joget install dir

start() {
        echo "Starting Joget Tomcat: "
        export JAVA_OPTS="-XX:MaxPermSize=128m -Xmx512M -Dwflow.home=./wflow/ "
        $CATALINA_HOME/bin/catalina.sh start
        echo "done."
}
stop() {
        echo "Shutting down Joget Tomcat: "
        $CATALINA_HOME/bin/catalina.sh stop
        echo "done."
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart)
        stop
        sleep 10
        #echo "Hard killing any remaining threads.."
        #kill -9 `cat $CATALINA_HOME/work/catalina.pid`
        start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
esac

exit 0
